spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        deny:
        login-username: admin
        login-password: admin
        reset-enable: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: false


mybatis-plus:
  mapper-locations: /mapper/*.xml