spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  redis:
#    database: 2
#    host: ${REDIS_HOST:localhost}
#    password:
#    port: ${REDIS_PORT:6379}
#    pool:
#    max-active: 20
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.98.100.3}:${MYSQL_PORT:3306}/loop_admin_v1?useUnicode=true&characterEncoding=UTF8
    username: zzy
    password: ZZY373890.
    #????????????????
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5                                       # ????????
      min-idle: 10                                          # ?????????
      max-active: 20                                        # ?????????
      max-wait: 60000                                       # ??????????????????
      min-evictable-idle-time-millis: 300000                # ???????????????????????????????
      time-between-eviction-runs-millis: 60000              # ??ò????????????????????????????????
      filters: stat,wall                                    # ????????????stat-???????log4j-?????wall-??????????SQL????????????????sql??????
      validation-query: SELECT 1 FROM DUAL                          # ??????????????? SQL???????????????????????
      test-on-borrow: false                                  # ????????????validationQuery??????????????????true???????????????
      test-on-return: false                                  # ??????????validationQuery??????????????????false???????????????
      test-while-idle: true                                 # ??????????????????????timeBetweenEvictionRunsMillis?????validationQuery??????????????????false???????????????????
      stat-view-servlet:
        enabled: true                                       # ????? StatViewServlet
        allow: 127.0.0.1                                    # ????????? ???????????127.0.0.1
        deny:                                               # ????????? ??????
        login-username: admin                               # ????????? ??????
        login-password: admin                               # ????????? ???????
        reset-enable: false
      filter:
        stat:
          enabled: true                                     # ????? FilterStat?????true
          log-slow-sql: true                                # ????? ??SQL ????????false
          slow-sql-millis: 5000                             # ?? SQL ????????? 3000???????????
          merge-sql: false                                  # ??????????????????????false


mybatis-plus:
  mapper-locations: /mapper/*.xml