server:
  port: 9003
spring:
  application:
    name: loop-admin
  redis:
    database: 2
    host: ${REDIS_HOST:47.98.100.3}
    password:
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/loop_admin_v1?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456



## 用户生成jwt字符串的secretKey
jwt:
  token-header: Authorization
  expire: 14400000 #四个小时
  rsa-secret: xx1WET12^%3^(WE45

#不需要登录验证的地址
url:
  ignore:
    startWith: /jwt